### ISSUE TITLE
Boot loop after restart in installation process

### ISSUE THREAD

**Issue by mfilatov** [AuroraStarry/RedmiBook16-Hackintosh#3]
It is not possible to continue the installation process after restart. There is boot loop with restarts.
Perhaps this is due to the new BIOS version (RMAIC6B0P0C0C)

**Comment by AuroraStarry** [comment]
> It is not possible to continue the installation process after restart. There is boot loop with restarts. Perhaps this is due to the new BIOS version (RMAIC6B0P0C0C)

Sorry, this item is no longer maintained and I no longer own this laptop
