### ISSUE TITLE
Battery

### ISSUE THREAD

**Issue by ArtMov19** [AuroraStarry/RedmiBook16-Hackintosh#4]
Need a dsdt patch for normal battery working?((
Bruh, I used your config, but it is frankly wrong for i7 1065g7.
I can share my bios mod to you...
Please tell me if you have hackintosh friends with this laptop? just need their config..  I've been looking for a month in all groups, forums, including Chinese onesI (

**Comment by AuroraStarry** [comment]
> Need a dsdt patch for normal battery working?(( Bruh, I used your config, but it is frankly wrong for i7 1065g7. I can share my bios mod to you... Please tell me if you have hackintosh friends with this laptop? just need their config.. I've been looking for a month in all groups, forums, including Chinese onesI (

At the time of my maintenance the `i5-1035G1` and `i7-1065G7` were maintained together (based on the original BIOS) and there may have been issues due to macOS updates. But I'm sorry, I no longer maintain

**Comment by AuroraStarry** [comment]
> Need a dsdt patch for normal battery working?(( Bruh, I used your config, but it is frankly wrong for i7 1065g7. I can share my bios mod to you... Please tell me if you have hackintosh friends with this laptop? just need their config.. I've been looking for a month in all groups, forums, including Chinese onesI (

At the time of my maintenance the i5-1035G1 and i7-1065G7 were maintained together (based on the original BIOS) and there may have been issues due to macOS updates. But I'm sorry, I no longer maintain

**Comment by ArtMov19** [comment]
Faking a native gpu , g7, is wrong, a dark other is also wrong.  Bruh, tell me, is your battery charging working?  Charging status appears?  It always run on battery and the percentages do not change.

**Comment by AuroraStarry** [comment]
> Faking native gpu , g7 , is wrong, many other things are also wrong, and maintaining together.  Bruh, tell me, is your battery charging working?  Charging status appears?  I always run on battery power and the percentages do not change. There are no problems with the new bios, they just took your old wrong config and tried to upgrade to ventura, which naturally does not boot.  Just tell me the battery, did it work completely fine?  the status was displayed ,,charging,,?

你说了两个问题：
1. i7-1065g7的核显，
2.电池状态

关于 i7-1065g7 我可以明确的告诉你，是正常的，也许我优化不好，但是在我维护期间的 Catalina， BigSur和 Monterey较早版本上，都能正常使用。

关于电池问题我可以肯定你换了 ACPIBatteryManager.kext 
那是我定制的kext，在Catalina， BigSur与Monterey上工作良好，充电状态，电量显示都没有问题。

你不要把新版本的macOS上新出的不兼容归到已经停止维护近一年的项目上。

**Comment by ArtMov19** [comment]
> > Faking native gpu , g7 , is wrong, many other things are also wrong, and maintaining together.  Bruh, tell me, is your battery charging working?  Charging status appears?  I always run on battery power and the percentages do not change. There are no problems with the new bios, they just took your old wrong config and tried to upgrade to ventura, which naturally does not boot.  Just tell me the battery, did it work completely fine?  the status was displayed ,,charging,,?
> 
> 你说了两个问题：
> 
> 1. i7-1065g7的核显，
>    2.电池状态
> 
> 关于 i7-1065g7 我可以明确的告诉你，是正常的，也许我优化不好，但是在我维护期间的 Catalina， BigSur和 Monterey较早版本上，都能正常使用。
> 
> 关于电池问题我可以肯定你换了 ACPIBatteryManager.kext 那是我定制的kext，在Catalina， BigSur与Monterey上工作良好，充电状态，电量显示都没有问题。
> 
> 你不要把新版本的macOS上新出的不兼容归到已经停止维护近一年的项目上。

Bruh, I respect you, but this is not normal, your igfx id is wrong, it turns native g7 into g4, because of this the gpu does not work properly.  4k video knocks out gpu)) Thank you so much for the reworked acpi battery manager, you are a hero.  Tell me, is only your converted kext enough for my config?  Or do you need something else, edits in ssdt?

**Comment by AuroraStarry** [comment]
I am very sorry for the use of translation in English.
I understand your question only now.

About the battery: you can try not replacing "ACPIBatteryManager.kext" (no other changes needed).
igfx id: It does not correspond, I seem to remember that I did it on purpose, but I don't remember why, because it's been too long.

Modified kext:
ACPIBatteryManager.kext //battery
CUSBP.kext //usb , used with XHCI-Injector

I can't remember about these because it's been too long, and using translations makes the communication ambiguous

**Comment by AuroraStarry** [comment]
This is the picture in my previous tutorial, you can look at the battery that, the status display is normal (the picture is a little blurry)
<img width="674" alt="屏幕截图 2023-02-20 180048" src="https://user-images.githubusercontent.com/79194954/220073824-d3286b04-e360-4fa7-bf9f-bea44d4de3ab.png">

**Comment by ArtMov19** [comment]
> This is the picture in my previous tutorial, you can look at the battery that, the status display is normal (the picture is a little blurry) <img alt="屏幕截图 2023-02-20 180048" width="674" src="https://user-images.githubusercontent.com/79194954/220073824-d3286b04-e360-4fa7-bf9f-bea44d4de3ab.png">

Thank you very much, you my hero.
