### ISSUE TITLE
作者你好，你有继续在更新吗？

### ISSUE THREAD

**Issue by Lance-He** [AuroraStarry/RedmiBook16-Hackintosh#5]
作者你好，macOS现已更新到13.3.1，有计划做更新么？
目前这版本已经很完美了，但是还是希望你能继续更新。
并且希望你能开通接受赞助渠道。

**Comment by AuroraStarry** [comment]
> 作者你好，macOS现已更新到13.3.1，有计划做更新么？ 目前这版本已经很完美了，但是还是希望你能继续更新。 并且希望你能开通接受赞助渠道。

你好，目前没有计划再更新了，因为我已经换了笔记本了，很抱歉
